stages:
- stage: GolangBuild
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage: ubuntu-latest

    steps:
    - script: |
        go build -o main main.go
      displayName: Build Go Project
