stages:
- stage: DotnetBuild
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage: ubuntu-latest

    steps:
    - script: |
        dotnet build --configuration Release
      displayName: Build .NET Project
    - script: |-
        dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
