parameters:
- name: language
  type: string
  default: java
- name: env
  type: string
  default: dev

stages:
- template: test-pipeline/stages/${{ parameters.language }}/build.yaml
  parameters:
    javaVersion: '17'

- template: test-pipeline/stages/${{ parameters.language }}/test.yaml
- template: test-pipeline/stages/deploy.yaml
  parameters:
    env: ${{ parameters.env }}

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(Build.SourcesDirectory)/test-pipeline
    artifact: test-pipeline
    publishLocation: pipeline
