stages:
- stage: JavaTests
  jobs:
  - job: Test
    displayName: Test Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "Running Java tests"
        mvn test
      displayName: Run Java Tests
    - script: |
        echo "Running post-deployment tests"
      displayName: Post-Deployment Tests
    - script: |
        echo "Cleaning up resources"
      displayName: Cleanup
